name = "LinearBand"
uuid = "e5cab26e-c5ce-48e0-bb1c-98fd263da73b"
authors = ["Allan R. Willms"]
version = "1.0.1"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.13"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
