name = "LinearBand"
uuid = "e5cab26e-c5ce-48e0-bb1c-98fd263da73b"
authors = ["Allan R. Willms"]
version = "1.0.0"

[compat]
julia = "1.6.7"
StaticArrays = "1.9.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
